name: Delete Backend in AWS for Terraform

on:
  # push:
  #   branches:
  #     - main   # or your preferred branch
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:

  Delete-terraform-backend:
    name: Delete S3 for TF Backend
    runs-on: ubuntu-latest
    # outputs:
    #   bucket_name: ${{ steps.bucket.outputs.bucket_name }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}

    # outputs:
    #   tfplan-path: ${{ steps.save-plan.outputs.tfplan }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Bucket Name from SSM Parameter
        run: |
          Bucket_VALUE=$(aws ssm get-parameter \
            --name "${{ vars.SSM_PARAMETER_NAME_BACKEND }}" \
            --with-decryption \
            --query "Parameter.Value" \
            --output text)
            
          echo "bucket_name=$Bucket_VALUE" >> $GITHUB_ENV

      - name: Delete S3 Bucket and SSM Parameter for State file
        # id: bucket
        run: |
          echo "Deleting objects from $bucket_name ..."
          aws s3 rm s3://$bucket_name --recursive
          aws s3api delete-objects --bucket $bucket_name --delete "$(aws s3api list-object-versions --bucket $bucket_name --output=json --query='{Objects: Versions[].{Key:Key,VersionId:VersionId}}')"
          echo "Deleting $bucket_name ..."
          aws s3api delete-bucket --bucket $bucket_name
          echo "Deleting SSM Parameter..."
          aws ssm delete-parameter \
            --name "${{ vars.SSM_PARAMETER_NAME_BACKEND }}"
